### ISSUE TITLE
Broken in python 3.9

### ISSUE THREAD

**Issue by jzbor** [Jojodicus/qr2eascii#1]
Stack trace:
```
Enter data to encode: asdfasdfasdfsd
Traceback (most recent call last):
  File "/home/cip/2021/wa94tiju/convert.py", line 20, in <module>
    image = qr.make_image(fill_color=(0, 0, 0), back_color=(255, 255, 255))
  File "/usr/lib/python3/dist-packages/qrcode/main.py", line 292, in make_image
    im = image_factory(
  File "/usr/lib/python3/dist-packages/qrcode/image/base.py", line 13, in __init__
    self._img = self.new_image(**kwargs)
  File "/usr/lib/python3/dist-packages/qrcode/image/pil.py", line 24, in new_image
    if fill_color.lower() != "black" or back_color.lower() != "white":
AttributeError: 'tuple' object has no attribute 'lower'
```

Please fix!1!!1!11

**Comment by jzbor** [comment]
Hoppala der CIP is schuld 🤷

**Comment by Jojodicus** [comment]
problem seems to be on your side, maybe try updating the qrcode package
closed for now
